export default {
  COLOR_PICKER: 'COLOR_PICKER',
  INPUT_NUMBER: 'INPUT_NUMBER',
  INPUT_TEXT: 'INPUT_TEXT',
  QUIZ_QUESTIONS: 'QUIZ_QUESTIONS',
  SELECT_BUTTON: 'SELECT_BUTTON',
  TEXTAREA: 'TEXTAREA',
  UPLOAD: 'UPLOAD'
}
