on: workflow_dispatch

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DEV_SSH_PRIVATE }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEV_HOST }} > ~/.ssh/known_hosts

      - name: connect, pull and build
        run: ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} "cd ${{ secrets.DEV_WORKDIR }} && git checkout dev && git pull && npm i && npm run build:dev && exit"

      - name: cleanup
        run: rm -rf ~/.ssh
