on: workflow_dispatch

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_PROD }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_PROD }} > ~/.ssh/known_hosts

      - name: connect, pull and build
        run: ssh ${{ secrets.USER_PROD }}@${{ secrets.HOST_PROD }} "cd ${{ secrets.WORKDIR_PROD }} && git checkout master && git pull && npm i && npm run build && exit"

      - name: cleanup
        run: rm -rf ~/.ssh
